parameters:
#    pug_al_odal.example.class: PugAl\Bundle\OdalBundle\Example

services:
#    pug_al_odal.example:
#        class: %pug_al_odal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
